---
meta:
  az: (( param "What availability zone is SHIELD deployed to?" ))

resource_pools:
- name:     small
  network:  bolo
  stemcell: (( grab meta.stemcell ))

  cloud_properties:
    instance_type: m3.medium
    availability_zone: (( grab meta.az ))
    ephemeral_disk:
      size: 20480
      type: gp2


compilation:
  network: bolo
  reuse_compilation_vms: true
  workers: 4

  cloud_properties:
  cloud_properties:
    instance_type: m3.large
    availability_zone: (( grab meta.az ))
    ephemeral_disk:
      size: 8192
      type: gp2

jobs:
- name: bolo
  resource_pool: small
